import "@/styles/globals.css";
import { AuthContextProvider } from "@/context/AuthContext"

import { GeistSans } from "geist/font/sans";
import Header from "@/components/Header";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <AuthContextProvider>
          <Header />
          <main className="pt-20 pb-10 px-3 max-w-5xl mx-auto">
            {children}
          </main>
        </AuthContextProvider>  
      </body>
    </html>
  );
}
